apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- github.com/kubeflow/manifests/applications/profiles/upstream/base?ref=v1.11.0
- stub-authorization-policy-crd.yaml
- kfam-service.yaml
- config-configmap.yaml

patchesStrategicMerge:
- kfam-patch.yaml

images:
- name: ghcr.io/kubeflow/kubeflow/profile-controller
  newName: ghcr.io/kubeflow/kubeflow/profile-controller
  newTag: v1.10.0
- name: ghcr.io/kubeflow/kubeflow/kfam
  newName: ghcr.io/kubeflow/kubeflow/kfam
  newTag: v1.10.0

commonLabels:
  kustomize.component: profiles
